In [2]:
import numpy as np
import pandas as pd
import os

In [204]:
# diretorio dos dados
root = 'PPG_ECG/bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv'

# todos os arquivos no diretório
paths = os.listdir(root)
paths.sort() # ordena as pastas

# filtra os sinais
path_signals = [os.path.join(root, path) for path in paths if 'Signals' in path]

print(f'Primeiro sinal: {path_signals[0]}')
print(f'Último sinal:   {path_signals[-1]}')

Primeiro sinal: bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv/bidmc_01_Signals.csv
Último sinal:   bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv/bidmc_53_Signals.csv


In [205]:
def create_windows(arr, size_win, hold=0):
    windows = list()  # Lista para armazenar as janelas geradas

    # Percorre o array com um passo de (tamanho da janela - hold)
    for w in range(0, arr.shape[0], size_win-hold):
        win = arr[w:w+size_win]  # cria uma janela de tamanho size_win

        # Verifica se a janela tem o tamanho exato
        if len(win) == size_win:  
            # Adiciona a janela à lista
            windows.append(win)  
    
    return np.array(windows)

In [206]:
arr = np.array(range(1, 11))

print('Dataset com janelamento (sem sobreposição):')

print(create_windows(arr, 5))
print('Dataset com janelamento (com sobreposição):')
print(create_windows(arr, 5, 4))

Dataset com janelamento (sem sobreposição):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dataset com janelamento (com sobreposição):
[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


In [207]:
def create_dataset_signal(path_signals, index, size_win=0, hold_size = 0, type_signal=' PLETH'):
    # carrega o csv
    df_signal = pd.read_csv(path_signals[index])
    
    # filtra a caracteristica utilizada
    if size_win > 0:
        values_arr = df_signal[type_signal].values #array dos valores

        # cria um dataframe em que as linhas são uma janela temporal
        windows = create_windows(values_arr, size_win, hold_size)
        df_signal = pd.DataFrame(windows)

    else:
        # sem janelamento
        df_signal = df_signal[[' PLETH']].T

    df_signal['label'] = index + 1 # label
        
    return df_signal

In [208]:
def create_dataset(path_signals, size_win=80, hold_size=0, type_signal=' PLETH'):
    n_register = len(path_signals) # numero de dados
    df = pd.DataFrame() # armazena todos os dasets

    for i in range(n_register):
        # cria o dataset de cada usuario
        df1 = create_dataset_signal(path_signals, index=i, size_win=size_win, 
                                    hold_size=hold_size, type_signal=type_signal)

        # concatena todos os datasets
        df = pd.concat((df, df1), axis=0)

    return df

In [210]:
df_ecg = create_dataset(path_signals, size_win=0, type_signal=' PLETH')
df_ppg = create_dataset(path_signals, size_win=0, type_signal=' II')

# save os de ppg e ecg
df_ecg.to_csv('ecg.csv', index=False)
df_ppg.to_csv('ppg.csv', index=False)

In [1]:
import pandas as pd

df_ECG = pd.read_csv('ecg.csv')

In [2]:
df_ECG

0        1        2        3        4        5        6        7  \
0   0.43597  0.43206  0.42815  0.42424  0.42131  0.41838  0.41740  0.41642   
1   0.63636  0.65689  0.67351  0.68817  0.69990  0.70870  0.71652  0.72043   
2   0.18866  0.20137  0.21994  0.25220  0.29717  0.35288  0.41740  0.48778   
3   0.67253  0.69892  0.72336  0.74291  0.75758  0.76833  0.77419  0.77517   
4   0.41642  0.41153  0.40665  0.40078  0.39492  0.38905  0.38416  0.37928   
5   0.30499  0.30694  0.30987  0.31183  0.31476  0.31672  0.31672  0.31672   
6   0.30303  0.29814  0.29326  0.28837  0.28446  0.28152  0.27859  0.27468   
7   0.63636  0.61779  0.59922  0.57771  0.55523  0.53275  0.51026  0.48974   
8   0.40274  0.39785  0.39394  0.39101  0.38710  0.38416  0.38025  0.37634   
9   0.36070  0.35582  0.35191  0.34800  0.34506  0.34311  0.34115  0.34018   
10  0.59922  0.59042  0.58260  0.57478  0.56696  0.56109  0.55621  0.55132   
11  0.59531  0.59042  0.58358  0.57771  0.57283  0.56891  0.56598  0.56207   
12  0.49658  0.49071  0.48485  0.47801  0.47116  0.46432  0.45748  0.45161   
13  0.60508  0.60117  0.59629  0.59042  0.58358  0.57576  0.56794  0.55914   
14  0.26882  0.26197  0.25806  0.25611  0.25611  0.25904  0.26882  0.28446   
15  0.33627  0.33333  0.33040  0.32747  0.32454  0.32160  0.31867  0.31476   
16  0.51026  0.50342  0.49462  0.48680  0.47996  0.47410  0.47019  0.46628   
17  0.39589  0.39296  0.39198  0.39101  0.39003  0.38905  0.38905  0.38905   
18  0.48583  0.48289  0.47898  0.47605  0.47410  0.47116  0.47019  0.46921   
19  0.38123  0.39785  0.41642  0.43695  0.45943  0.48192  0.50440  0.52493   
20  0.41447  0.41153  0.40958  0.40762  0.40665  0.40665  0.40665  0.40567   
21  0.43109  0.42913  0.42717  0.42717  0.42620  0.42326  0.42131  0.41838   
22  0.74585  0.73998  0.73021  0.71750  0.70283  0.68622  0.66862  0.65005   
23  0.64321  0.64614  0.64809  0.64712  0.64516  0.64125  0.63441  0.62659   
24  0.54643  0.55230  0.55523  0.55621  0.55523  0.55230  0.54839  0.54252   
25  0.52981  0.52688  0.52395  0.52004  0.51711  0.51417  0.51222  0.51026   
26  0.65396  0.68231  0.70479  0.72239  0.73412  0.74291  0.74878  0.75073   
27  0.62366  0.62757  0.63050  0.63148  0.63245  0.63245  0.63245  0.63050   
28  0.27370  0.26784  0.26295  0.26002  0.25611  0.25318  0.24927  0.24633   
29  0.66667  0.65103  0.63441  0.61877  0.60313  0.58553  0.56696  0.54741   
30  0.62366  0.62952  0.63539  0.64027  0.64418  0.64809  0.65103  0.65396   
31  0.50049  0.49756  0.49462  0.49169  0.48778  0.48485  0.48289  0.47996   
32  0.31085  0.31085  0.30987  0.30987  0.30987  0.31085  0.31085  0.31085   
33  0.68915  0.67937  0.66569  0.65103  0.63734  0.62463  0.61095  0.59824   
34  0.78690  0.80352  0.81427  0.82405  0.83089  0.83480  0.83578  0.83382   
35  0.22581  0.22385  0.22190  0.22092  0.21994  0.21799  0.21701  0.21603   
36  0.48680  0.46921  0.45259  0.43988  0.42815  0.41740  0.40665  0.39687   
37  0.45943  0.45259  0.44673  0.44086  0.43597  0.43109  0.44086  0.45748   
38  0.45455  0.44966  0.44673  0.44379  0.44477  0.44770  0.45357  0.46237   
39  2.31090  2.29420  2.27370  2.24630  2.21700  2.18670  2.14660  2.09970   
40  0.48876  0.48289  0.47801  0.47312  0.47019  0.46628  0.46237  0.45748   
41  2.66860  2.62370  2.57580  2.52300  2.46530  2.40370  2.33820  2.26880   
42  0.68719  0.68328  0.68035  0.67742  0.67351  0.66764  0.65982  0.65103   
43  2.03620  2.08110  2.12020  2.15250  2.18180  2.20530  2.22090  2.23360   
44  1.91590  1.90620  1.89150  1.87190  1.84850  1.81920  1.79370  1.77130   
45  1.81620  1.77710  1.74190  1.71070  1.68720  1.66760  1.64710  1.62760   
46  2.17600  2.13590  2.09680  2.05470  2.00880  1.96190  1.91400  1.86900   
47  2.74490  2.85240  2.91300  2.92670  2.89740  2.83680  2.75270  2.65490   
48  0.30401  0.29912  0.29619  0.29326  0.29130  0.29032  0.29032  0.29130   
49  0.56500  0.56891  0.57185  0.57380  0.57380  0.57380  0.57380  0.57185   
50  0.59531  0.57967  0.56403  0